-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Aani CASCADE;
DROP TABLE IF EXISTS Vaihtoehto CASCADE;
DROP TABLE IF EXISTS Aanestaneet CASCADE; 
DROP TABLE IF EXISTS Aanestys CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;  